import numpy as np
max_atol = 0 #0
max_rtol = 0.001 #0.001

default_compare_test_kwargs = {"correct_V":True,
                               "correct_t1":False,
                               "perform_GLRT":False,
                               "nR":250,
                               "n_c":10,
                               "alpha":0.05,
                               "grid":'JJJ1',
                               "a":1e-7,
                               "b":1e7,
                               "df":40,
                               "verbose":False,
                               "drop_NA":True,
                               "method":"Chol",
                               "seed":None,
                               "only_expected_edf":False,
                               "Vp_fidiff":False,
                               "use_importance_weights":True,
                               "prior":None,
                               "recompute_H":False}

default_gamm_test_kwargs = {"max_outer":50,
                            "max_inner":100,
                            "conv_tol":1e-7,
                            "extend_lambda":True,
                            "control_lambda":True,
                            "exclude_lambda":False,
                            "extension_method_lam" : "nesterov",
                            "restart":False,
                            "method":"Chol",
                            "check_cond":1,
                            "progress_bar":True,
                            "n_cores":10,
                            "offset" : None}

default_gammlss_test_kwargs = {"max_outer":50,
                               "max_inner":200,
                               "min_inner":200,
                               "conv_tol":1e-7,
                               "extend_lambda":True,
                               "extension_method_lam":"nesterov2",
                               "control_lambda":1,
                               "restart":False,
                               "method":"Chol",
                               "check_cond":1,
                               "piv_tol":np.power(np.finfo(float).eps,0.04),
                               "should_keep_drop":True,
                               "prefit_grad":False,
                               "repara":False,
                               "progress_bar":True,
                               "n_cores":10,
                               "seed":0,
                               "init_lambda":None}

default_gsmm_test_kwargs = {"init_coef":None,
                            "max_outer":50,
                            "max_inner":200,
                            "min_inner":200,
                            "conv_tol":1e-7,
                            "extend_lambda":True,
                            "extension_method_lam":"nesterov2",
                            "control_lambda":1,
                            "restart":False,
                            "optimizer":"Newton",
                            "method":"Chol",
                            "check_cond":1,
                            "piv_tol":np.power(np.finfo(float).eps,0.04),
                            "progress_bar":False,
                            "n_cores":10,
                            "seed":0,
                            "drop_NA":True,
                            "init_lambda":None,
                            "form_VH":True,
                            "use_grad":False,
                            "build_mat":None,
                            "should_keep_drop":True,
                            "gamma":1,
                            "qEFSH":'SR1',
                            "overwrite_coef":True,
                            "max_restarts":0,
                            "qEFS_init_converge":True,
                            "prefit_grad":False,
                            "repara":False,
                            "init_bfgs_options":None}